console.log("type conversions");
console.log("non-string to string type");
let age = 23;
let ageString = String(age);
console.log(typeof ageString);
console.log("non-number to number type");
let ageNumber = Number("ajn");
console.log(ageNumber);
console.log(typeof ageNumber);
console.log(Number(false));
console.log(Number(true));
console.log(Number(undefined));
console.log(Number(null));
console.log(Boolean(NaN));
console.log(Boolean(34));
console.log(Boolean(0));
console.log(Boolean({}));
console.log(Boolean([]));
console.log(Boolean("0"));
console.log(Boolean(" "));
